// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const MCP_BUILD_FINGERPRINT = "sha256:41512aae0ceecdc5911e86e06285899ec2eb8605cd4023988e3271eeb6171d4c" as const;
export const MCP_PACKAGE_VERSION = "0.4.0" as const;
