// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const MCP_BUILD_FINGERPRINT = "sha256:6f222f48ce5404e47f20918c61238bfa505a1254025385002123fb89af6e0c30" as const;
export const MCP_PACKAGE_VERSION = "0.4.0" as const;
