// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const MCP_BUILD_FINGERPRINT = "sha256:e065e69a37d8cee1071a8d29f5df1ef962d20d2c7de08649fba568ae7e508c71" as const;
export const MCP_PACKAGE_VERSION = "0.4.0" as const;
