import type { RestorationProfile } from './types.js';

export const genericProfile: RestorationProfile = {
  id: 'generic',
  displayName: 'Generic',
  targetSymbols: [
    { symbol: 'AppBar', role: 'app-bar', reason: 'Flutter Material app bar candidate.', generic: true },
    { symbol: 'Scaffold', role: 'page-base', reason: 'Flutter Material page shell candidate.', generic: true },
    { symbol: 'TextButton', role: 'button', reason: 'Flutter Material text button candidate.', generic: true },
    { symbol: 'GestureDetector', role: 'button', reason: 'Flutter interaction wrapper candidate.', generic: true },
    { symbol: 'Image.asset', role: 'image', reason: 'Flutter local asset image candidate.', generic: true },
    { symbol: 'showModalBottomSheet', role: 'sheet', reason: 'Flutter Material bottom sheet candidate.', generic: true },
    { symbol: 'ListView', role: 'refresh', reason: 'Flutter list candidate.', generic: true },
    { symbol: 'RefreshIndicator', role: 'refresh', reason: 'Flutter pull-to-refresh candidate.', generic: true },
    { symbol: 'Theme.of(context)', role: 'theme', reason: 'Flutter Material theme candidate.', generic: true },
    { symbol: 'Navigator.pushNamed', role: 'route', reason: 'Flutter Navigator named route candidate.', generic: true },
    { symbol: 'Navigator.pop', role: 'route', reason: 'Flutter Navigator back candidate.', generic: true },
  ],
  roleSymbols: {
    'app-bar': ['AppBar'],
    button: ['TextButton', 'GestureDetector'],
    image: ['Image.asset'],
    sheet: ['showModalBottomSheet'],
    'page-base': ['Scaffold'],
    refresh: ['ListView', 'RefreshIndicator'],
    theme: ['Theme.of(context)'],
    route: ['Navigator.pushNamed', 'Navigator.pop'],
  },
  patternSymbols: [
    { pattern: /record|list|history/, symbols: ['ListView', 'RefreshIndicator'] },
    { pattern: /detail/, symbols: ['AppBar', 'Scaffold'] },
    { pattern: /form/, symbols: ['TextButton', 'showModalBottomSheet'] },
  ],
  usageSymbols: {
    theme: ['Theme.of(context)'],
    route: ['Navigator.pushNamed', 'Navigator.pop'],
    i18n: [],
  },
  sourceLexicon: {
    sectionClassTerms: [
      'section',
      'card',
      'panel',
      'list',
      'chart',
      'tab',
      'tabs',
      'header',
      'nav',
      'bottom-bar',
      'footer',
      'modal',
      'popup',
      'sheet',
      'metric',
      'history',
      'filter',
      'search',
      'sort',
    ],
    chartTerms: ['chart', 'donut', 'bar-chart', 'trend', 'indicator'],
    listTerms: ['list', 'row', 'rows', 'table', 'flow'],
    sectionTerms: ['section', 'card', 'panel', 'history', 'metric', 'metrics', 'info'],
    summaryTerms: ['summary', 'info'],
    bottomActionTerms: ['bottom-bar', 'footer-action', 'fixed-footer'],
    dynamicQuantityTerms: ['qty', 'quantity', 'count'],
    listHeadingTerms: ['records', 'history', 'list'],
    mockDataTerms: ['mock', 'data', 'list', 'rows', 'history', 'metrics', 'flow'],
    navigationTerms: ['route', 'query', 'anchor'],
    chartDataTerms: ['chart', 'donut', 'bar', 'path', 'data', 'limit', 'min', 'max'],
    tradeTerms: [],
    portfolioTerms: [],
    authTerms: ['login', 'auth', 'password', 'otp', 'verify'],
    wizardTerms: ['step', 'wizard', 'next', 'previous', 'progress'],
    articleTerms: ['article', 'news', 'notice', 'message', 'detail'],
    statusTerms: [],
  },
};
