import { genericProfile } from './generic.js';
import type { RestorationProfile } from './types.js';

export const youfiColorTokenMap: Record<string, string> = {
  '--color-primary-normal': 'themeService.colors.colorPrimaryNormal',
  '--color-primary-pressed': 'themeService.colors.colorPrimaryPressed',
  '--color-text-normal': 'themeService.colors.colorTextNormal',
  '--color-text-title': 'themeService.colors.colorTextTitle',
  '--color-text-regular': 'themeService.colors.colorTextRegular',
  '--color-text-description': 'themeService.colors.colorTextDescription',
  '--color-text-secondary': 'themeService.colors.colorTextSecondary',
  '--color-text-label': 'themeService.colors.colorTextLabel',
  '--color-text-light': 'themeService.colors.colorTextLight',
  '--color-text-light-1': 'themeService.colors.colorTextLight1',
  '--color-bg-base': 'themeService.colors.colorBgBase',
  '--color-bg-1': 'themeService.colors.colorBg1',
  '--color-bg-surface-1': 'themeService.colors.colorBgSurface1',
  '--color-bg-surface-2': 'themeService.colors.colorBgSurface2',
  '--color-sheet-bg': 'themeService.colors.colorSheetBg',
  '--color-popup-bg': 'themeService.colors.colorPopupBg',
  '--color-bg-mask-1': 'themeService.colors.colorBgMask1',
  '--color-bg-mask-2': 'themeService.colors.colorBgMask2',
  '--color-light-line': 'themeService.colors.colorLightLine',
  '--color-heavy-line': 'themeService.colors.colorHeavyLine',
  '--color-disabled': 'themeService.colors.colorDisabled',
  '--color-warning': 'themeService.colors.colorWarning',
  '--color-error': 'themeService.colors.colorError',
  '--color-redpoint': 'themeService.colors.colorRedpoint',
  '--color-succeed': 'themeService.colors.colorSucceed',
  '--color-icon-brand': 'themeService.colors.colorIconBrand',
  '--color-icon-default': 'themeService.colors.colorIconDefault',
  '--color-icon-secondary': 'themeService.colors.colorIconSecondary',
  '--color-icon-primary': 'themeService.colors.colorIconPrimary',
  '--color-icon-disabled': 'themeService.colors.colorIconDisabled',
  '--color-icon-purple': 'themeService.colors.colorIconPurple',
  '--color-button-brand': 'themeService.colors.colorButtonBrand',
  '--color-button-disabled': 'themeService.colors.colorButtonDisabled',
  '--color-trend-red-1': 'themeService.colors.colorTrendRed1',
  '--color-trend-red-2': 'themeService.colors.colorTrendRed2',
  '--color-trend-red-3': 'themeService.colors.colorTrendRed3',
  '--color-trend-green-1': 'themeService.colors.colorTrendGreen1',
  '--color-trend-green-2': 'themeService.colors.colorTrendGreen2',
  '--color-trend-green-3': 'themeService.colors.colorTrendGreen3',
  '--color-trend-flat': 'themeService.colors.colorTrendFlat',
  '--color-trend-up-disabled': 'themeService.colors.colorTrendUpDisabled',
  '--color-trend-down-disabled': 'themeService.colors.colorTrendDownDisabled',
  '--color-chart-line-1': 'themeService.colors.colorChartLine1',
  '--color-chart-line-2': 'themeService.colors.colorChartLine2',
  '--color-chart-line-3': 'themeService.colors.colorChartLine3',
  '--color-chart-line-4': 'themeService.colors.colorChartLine4',
  '--color-chart-line-5': 'themeService.colors.colorChartLine5',
  '--color-chart-line-6': 'themeService.colors.colorChartLine6',
  '--color-chart-line-7': 'themeService.colors.colorChartLine7',
  '--color-favourite': 'themeService.colors.colorFavourite',
};

export const youfiTypographyTokenMap: Record<string, string> = {
  'headline-b': 'themeService.textStyles.headlineB',
  'headline-m': 'themeService.textStyles.headlineM',
  'title-b': 'themeService.textStyles.titleB',
  'title-m': 'themeService.textStyles.titleM',
  'body-m': 'themeService.textStyles.bodyM',
  'body-r': 'themeService.textStyles.bodyR',
  'small1-m': 'themeService.textStyles.small1M',
  'small1-r': 'themeService.textStyles.small1R',
  'small2-r': 'themeService.textStyles.small2R',
  'small3-r': 'themeService.textStyles.small3R',
  'small4-r': 'themeService.textStyles.small4R',
  'small4-m': 'themeService.textStyles.small4M',
  'number1-b': 'themeService.textStyles.number1B',
  'number2-b': 'themeService.textStyles.number2B',
  'number3-b': 'themeService.textStyles.number3B',
  'tab-b': 'themeService.textStyles.tabB',
  'tab-m': 'themeService.textStyles.tabM',
};

export const youfiColorTokenValues: Record<string, string> = {
  '--color-primary-normal': '#1a2028',
  '--color-primary-pressed': '#0f1217',
  '--color-text-normal': '#1a2028',
  '--color-text-title': '#1a2028',
  '--color-text-regular': '#1a2028',
  '--color-text-description': '#6b707f',
  '--color-text-secondary': '#9a9fa5',
  '--color-text-label': '#c6c8cb',
  '--color-text-light': '#ffffff',
  '--color-text-light-1': '#ffffff',
  '--color-bg-base': '#ffffff',
  '--color-bg-1': '#f1f1f1',
  '--color-bg-surface-1': '#f8f8f9',
  '--color-bg-surface-2': '#f8f8f9',
  '--color-sheet-bg': '#ffffff',
  '--color-popup-bg': '#ffffff',
  '--color-bg-mask-1': '#1a20288c',
  '--color-bg-mask-2': '#1a20282d',
  '--color-light-line': '#f1f1f1',
  '--color-heavy-line': '#eeeeee',
  '--color-disabled': '#bfc1c5',
  '--color-warning': '#ff175266',
  '--color-error': '#ff1752',
  '--color-redpoint': '#ff1752',
  '--color-succeed': '#00b98b',
  '--color-icon-brand': '#1a2028',
  '--color-icon-default': '#5e00ff',
  '--color-icon-secondary': '#6d7279',
  '--color-icon-primary': '#6d7279',
  '--color-icon-disabled': '#bfc1c5',
  '--color-icon-purple': '#5e00ff',
  '--color-button-brand': '#1a2028',
  '--color-button-disabled': '#bfc1c5',
  '--color-trend-red-1': '#f41c53',
  '--color-trend-red-2': '#f41c5314',
  '--color-trend-red-3': '#f41c531e',
  '--color-trend-green-1': '#00ac6d',
  '--color-trend-green-2': '#00ac6d14',
  '--color-trend-green-3': '#00ac6d1e',
  '--color-trend-flat': '#616f85',
  '--color-trend-up-disabled': '#f2b1cb',
  '--color-trend-down-disabled': '#b2e6d3',
  '--color-chart-line-1': '#7e3eff',
  '--color-chart-line-2': '#ec00ff',
  '--color-chart-line-3': '#f47927',
  '--color-chart-line-4': '#ffbf00',
  '--color-chart-line-5': '#e8d639',
  '--color-chart-line-6': '#8bbb11',
  '--color-chart-line-7': '#349dff',
  '--color-favourite': '#ff7300',
};

export const youfiTypographyTokenValues: Record<string, string> = {
  'headline-b': '17px/22px/700',
  'headline-m': '17px/22px/500',
  'title-b': '20px/28px/700',
  'title-m': '20px/28px/500',
  'body-m': '15px/20px/500',
  'body-r': '15px/20px/400',
  'small1-m': '13px/16px/500',
  'small1-r': '13px/16px/400',
  'small2-r': '12px/16px/400',
  'small3-r': '11px/14px/400',
  'small4-r': '10px/14px/400',
  'small4-m': '10px/14px/500',
  'number1-b': '34px/46px/700',
  'number2-b': '30px/40px/700',
  'number3-b': '24px/32px/700',
  'tab-b': '18px/24px/700',
  'tab-m': '18px/24px/500',
};

const youfiTargetSymbols: RestorationProfile['targetSymbols'] = [
  { symbol: 'CommonAppBar', role: 'app-bar', reason: 'YouFi app bar candidate.' },
  { symbol: 'CommonButton', role: 'button', reason: 'YouFi button candidate.' },
  { symbol: 'CommonImage', role: 'image', reason: 'YouFi image candidate.' },
  { symbol: 'CommonSvg', role: 'image', reason: 'YouFi SVG candidate.' },
  { symbol: 'CommonNetImage', role: 'image', reason: 'YouFi network image candidate.' },
  { symbol: 'CommonEmpty', role: 'empty', reason: 'YouFi empty-state candidate.' },
  { symbol: 'CommonLoading', role: 'loading', reason: 'YouFi loading candidate.' },
  { symbol: 'CommonToast', role: 'toast', reason: 'YouFi toast candidate.' },
  { symbol: 'Pop.sheet', role: 'sheet', reason: 'YouFi sheet/popup candidate.' },
  { symbol: 'YouFiPop', role: 'sheet', reason: 'YouFi popup candidate.' },
  { symbol: 'BaseGetView', role: 'page-base', reason: 'YouFi page base class candidate.' },
  { symbol: 'BaseGetPullView', role: 'page-base', reason: 'YouFi pull-to-refresh page base candidate.' },
  { symbol: 'SmartRefresher', role: 'refresh', reason: 'YouFi refresh/list paging candidate.' },
  { symbol: 'themeService.colors', role: 'theme', reason: 'YouFi color token usage.' },
  { symbol: 'themeService.textStyles', role: 'theme', reason: 'YouFi text style usage.' },
  { symbol: '.tr', role: 'i18n', reason: 'GetX translation usage.' },
  { symbol: 'Get.toNamed', role: 'route', reason: 'GetX named route navigation usage.' },
  { symbol: 'Get.back', role: 'route', reason: 'GetX back navigation usage.' },
];

export const youfiProfile: RestorationProfile = {
  ...genericProfile,
  id: 'youfi',
  displayName: 'YouFi',
  aliases: ['youfi', 'youfi-app'],
  moduleAliases: {
    stock: 'order',
    options: 'option',
    'options-trade': 'option',
    account: 'account',
    asset: 'account',
    security: 'auth',
    onboard: 'account',
  },
  targetSymbols: [
    ...youfiTargetSymbols,
    ...(genericProfile.targetSymbols ?? []),
  ],
  roleSymbols: {
    ...genericProfile.roleSymbols,
    'app-bar': ['CommonAppBar', 'AppBar'],
    button: ['CommonButton', 'TextButton', 'GestureDetector'],
    image: ['CommonImage', 'CommonSvg', 'CommonNetImage', 'Image.asset'],
    empty: ['CommonEmpty'],
    loading: ['CommonLoading'],
    sheet: ['Pop.sheet', 'YouFiPop', 'showModalBottomSheet'],
    toast: ['CommonToast'],
    'page-base': ['BaseGetView', 'BaseGetPullView', 'GetView', 'Scaffold'],
    refresh: ['SmartRefresher', 'RefreshController', 'ListView'],
    theme: ['themeService.colors', 'themeService.textStyles', 'Theme.of(context)'],
    i18n: ['.tr'],
    route: ['Get.toNamed', 'Get.back', 'Routes.', 'Navigator.pushNamed', 'Navigator.pop'],
  },
  patternSymbols: [
    { pattern: /record|list|history/, symbols: ['SmartRefresher', 'ListView', 'CommonEmpty', 'CommonLoading'] },
    { pattern: /quote|detail|trade/, symbols: ['CommonAppBar', 'AppBar', 'Scaffold'] },
    { pattern: /form|ticket|auth/, symbols: ['CommonButton', 'TextButton', 'showModalBottomSheet'] },
    ...(genericProfile.patternSymbols ?? []),
  ],
  usageSymbols: {
    theme: ['themeService.colors', 'themeService.textStyles', 'Theme.of(context)'],
    route: ['Get.toNamed', 'Get.back', 'Routes.', 'Navigator.pushNamed', 'Navigator.pop'],
    i18n: ['.tr'],
  },
  themeTokens: {
    colors: youfiColorTokenMap,
    colorValues: youfiColorTokenValues,
    typography: youfiTypographyTokenMap,
    typographyValues: youfiTypographyTokenValues,
  },
  sourceLexicon: {
    ...(genericProfile.sourceLexicon ?? {}),
    sectionClassTerms: [
      ...(genericProfile.sourceLexicon?.sectionClassTerms ?? []),
      'quote',
      'price',
      'holding',
      'profile',
    ],
    chartTerms: [
      ...(genericProfile.sourceLexicon?.chartTerms ?? []),
      'kline',
      'rsi',
      'macd',
      'kdj',
      'ma',
    ],
    listTerms: [
      ...(genericProfile.sourceLexicon?.listTerms ?? []),
      'holding',
      'holdings',
      'order-book',
    ],
    sectionTerms: [
      ...(genericProfile.sourceLexicon?.sectionTerms ?? []),
      'profile',
      'objective',
      'quote',
      'price',
    ],
    summaryTerms: ['price', 'quote', 'summary', 'info'],
    bottomActionTerms: [
      ...(genericProfile.sourceLexicon?.bottomActionTerms ?? []),
      'trade-action',
    ],
    dynamicQuantityTerms: ['held', 'qty', 'quantity', 'shares', '持股', '持仓', '数量', '可用'],
    listHeadingTerms: ['positions', 'records', 'history', 'orders', 'list', '持仓', '记录', '历史', '列表', '可行权', '行权'],
    mockDataTerms: [
      ...(genericProfile.sourceLexicon?.mockDataTerms ?? []),
      'holdings',
      'sectors',
      'profile',
      'quote',
      'book',
    ],
    navigationTerms: [
      ...(genericProfile.sourceLexicon?.navigationTerms ?? []),
      'ticker',
    ],
    chartDataTerms: [
      ...(genericProfile.sourceLexicon?.chartDataTerms ?? []),
      'kline',
      'rsi',
      'macd',
      'kdj',
      'ma',
    ],
    tradeTerms: ['trade', 'order', 'buy', 'sell', 'option', 'quote', 'ticker', 'price', 'kline', 'holding', 'fund', 'etf', 'stock'],
    portfolioTerms: ['asset', 'portfolio', 'position', 'balance', 'holding', 'funds', 'account'],
    authTerms: ['login', 'auth', 'password', 'otp', 'verify', 'security', 'onboard', 'kyc'],
    wizardTerms: ['step', 'wizard', 'next', 'previous', 'progress', 'onboard'],
    articleTerms: ['article', 'news', 'notice', 'message', 'detail', 'profile', 'objective'],
    statusTerms: ['ITM', 'OTM', 'ATM'],
    timeBadgePattern: '^\\d+D$',
  },
};
