export type {
  AssetEvidence,
  CapturePageSnapshotInput,
  CapturePageSnapshotResult,
  CapturePrototypePageInput,
  CaptureResult,
  DomNodeSnapshot,
  InteractionEvidence,
  OcrResult,
  OcrScreenshotInput,
  OcrScreenshotResult,
  OcrTextBox,
  PageSnapshot,
  PageSnapshotNode,
  SnapshotComputedStyle,
  SnapshotNodeRole,
  SnapshotSourceKind,
  VisualSection,
  VisualTokenEvidence,
} from '../types/index.js';
