export type {
  AssetEvidence,
  CapturePageEvidenceInput,
  CapturePageEvidenceResult,
  CapturePrototypePageInput,
  CaptureResult,
  DetectedCapabilities,
  DomNodeSnapshot,
  InteractionEvidence,
  OcrResult,
  OcrScreenshotInput,
  OcrScreenshotResult,
  OcrTextBox,
  PageEvidence,
  PageSnapshotNode,
  SnapshotComputedStyle,
  SnapshotNodeRole,
  SnapshotSourceKind,
  VisualSection,
  VisualTokenEvidence,
} from '../types/index.js';
