import type { Component } from "vue";
import {
  AlertCircle,
  AlertTriangle,
  Check,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  Clock3,
  Copy,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  FolderOpen,
  Footprints,
  Home,
  Inbox,
  List,
  MapPin,
  MoreHorizontal,
  PersonStanding,
  Plus,
  RefreshCw,
  Radio,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Thermometer,
  Truck,
  User,
  X,
} from "lucide-vue-next";

/** Curated Lucide ids used by PBWork DS. Stable across Vue / Flutter sync. */
export const PB_ICON_NAMES = [
  "more",
  "plus",
  "search",
  "settings",
  "home",
  "list",
  "user",
  "inbox",
  "check",
  "chevron-down",
  "chevron-right",
  "alert-triangle",
  "alert-circle",
  "clock",
  "refresh-cw",
  "clipboard-check",
  "shield-check",
  "folder-open",
  "thermometer",
  "snowflake",
  "copy",
  "file-text",
  "sliders-horizontal",
  "map-pin",
  "radio",
  "truck",
  "dumbbell",
  "eye",
  "eye-off",
  "footprints",
  "person-standing",
  "sparkles",
  "x",
] as const;

export type PbIconName = (typeof PB_ICON_NAMES)[number];

const ICON_MAP: Record<PbIconName, Component> = {
  more: MoreHorizontal,
  plus: Plus,
  search: Search,
  settings: Settings,
  home: Home,
  list: List,
  user: User,
  inbox: Inbox,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  clock: Clock3,
  "refresh-cw": RefreshCw,
  "clipboard-check": ClipboardCheck,
  "shield-check": ShieldCheck,
  "folder-open": FolderOpen,
  thermometer: Thermometer,
  snowflake: Snowflake,
  copy: Copy,
  "file-text": FileText,
  "sliders-horizontal": SlidersHorizontal,
  "map-pin": MapPin,
  radio: Radio,
  truck: Truck,
  dumbbell: Dumbbell,
  eye: Eye,
  "eye-off": EyeOff,
  footprints: Footprints,
  "person-standing": PersonStanding,
  sparkles: Sparkles,
  x: X,
};

export function resolvePbIcon(name: PbIconName | undefined): Component {
  return ICON_MAP[name ?? "more"] ?? MoreHorizontal;
}

export function isPbIconName(value: string): value is PbIconName {
  return (PB_ICON_NAMES as readonly string[]).includes(value);
}
