import type { ComponentRecord } from "@/design-system/types";
import { COLOR_TOKEN_SELECT_OPTIONS } from "@/design-system/components/_shared/colorTokens";
import { PB_ICON_NAMES } from "@/design-system/components/_shared/icons";

const toneOptions = [
  { label: "Primary (color.primary)", value: "primary" },
  { label: "Secondary (color.secondary)", value: "secondary" },
  { label: "Error (color.error)", value: "error" },
  { label: "Success (color.success)", value: "success" },
];

const sizeOptions = [
  { label: "小", value: "sm" },
  { label: "标准", value: "md" },
  { label: "大", value: "lg" },
];

const colorTokenOptions = COLOR_TOKEN_SELECT_OPTIONS;
const iconOptions = PB_ICON_NAMES.map((name) => ({ label: name, value: name }));

export const componentRecords = [
  {
    id: "button",
    label: "Button",
    description: "表单主次操作，如提交工单、保存草稿。",
    category: "action",
    view: "action/Button.vue",
    contract: "contracts/button.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "bgColor",
        label: "背景 Token",
        control: "select",
        options: colorTokenOptions,
      },
      {
        key: "borderColor",
        label: "边框 Token",
        control: "select",
        options: colorTokenOptions,
      },
      {
        key: "textColor",
        label: "文字 Token",
        control: "select",
        options: colorTokenOptions,
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "block", label: "占满宽度", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "icon",
    label: "Icon",
    description: "Lucide 常用图标；按稳定 name 渲染，尺寸与颜色走 Token。",
    category: "action",
    view: "action/Icon.vue",
    contract: "contracts/icon.json",
    example: {},
    controls: [
      {
        key: "name",
        label: "图标",
        control: "select",
        options: iconOptions,
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      {
        key: "tone",
        label: "颜色",
        control: "select",
        options: [
          { label: "继承", value: "inherit" },
          { label: "正文", value: "on-surface" },
          { label: "弱化", value: "muted" },
          { label: "主色", value: "primary" },
          { label: "行动", value: "action" },
          { label: "错误", value: "error" },
          { label: "成功", value: "success" },
          { label: "警告", value: "warning" },
        ],
      },
      { key: "label", label: "无障碍名称", control: "text" },
    ],
  },
  {
    id: "icon-button",
    label: "Icon Button",
    description: "顶栏与工具区的紧凑图标操作，如更多、新建。",
    category: "action",
    view: "action/IconButton.vue",
    contract: "contracts/icon-button.json",
    example: {},
    controls: [
      { key: "ariaLabel", label: "无障碍名称", control: "text" },
      {
        key: "icon",
        label: "图标",
        control: "select",
        options: iconOptions,
      },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "SM", value: "sm" },
          { label: "MD", value: "md" },
          { label: "LG", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          { label: "Secondary (color.secondary)", value: "secondary" },
          { label: "Primary (color.primary)", value: "primary" },
        ],
      },
      {
        key: "variant",
        label: "样式",
        control: "select",
        options: [
          { label: "柔和背景", value: "tonal" },
          { label: "实色背景", value: "flat" },
          { label: "描边", value: "outlined" },
          { label: "透明", value: "text" },
        ],
      },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "text-field",
    label: "Text Field",
    description: "采集单行业务信息，如联系人、电话。",
    category: "input",
    view: "input/TextField.vue",
    contract: "contracts/text-field.json",
    example: {},
    controls: [
      { key: "label", label: "标签", control: "text" },
      { key: "showLabel", label: "显示标签", control: "boolean" },
      { key: "modelValue", label: "值", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "textarea",
    label: "Textarea",
    description: "填写多行说明，如问题描述、现场备注。",
    category: "input",
    view: "input/Textarea.vue",
    contract: "contracts/textarea.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "showLabel", label: "显示标签", control: "boolean" },
      { key: "modelValue", label: "输入内容", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "search-bar",
    label: "Search Bar",
    description: "在列表顶部按编号或客户搜索，支持清除。",
    category: "input",
    view: "input/SearchBar.vue",
    contract: "contracts/search-bar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "搜索内容", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "checkbox",
    label: "Checkbox",
    description: "独立确认项，如提交前核对、业务偏好勾选。",
    category: "input",
    view: "input/Checkbox.vue",
    contract: "contracts/checkbox.json",
    example: {},
    controls: [
      { key: "label", label: "选项文案", control: "text" },
      { key: "modelValue", label: "已选中", control: "boolean" },
      {
        key: "selectedColor",
        label: "选中色 Token",
        control: "select",
        options: colorTokenOptions.filter(
          (item) => item.value !== "transparent",
        ),
      },
      {
        key: "uncheckedBorderColor",
        label: "未选中边框 Token",
        control: "select",
        options: colorTokenOptions.filter(
          (item) => item.value !== "transparent",
        ),
      },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "radio-group",
    label: "Radio Group",
    description: "互斥单选，如工单优先级、上门时段。",
    category: "input",
    view: "input/RadioGroup.vue",
    contract: "contracts/radio-group.json",
    example: {},
    controls: [
      { key: "label", label: "分组名称", control: "text" },
      { key: "modelValue", label: "当前选项", control: "text" },
      {
        key: "color",
        label: "选中色 Token",
        control: "select",
        options: colorTokenOptions.filter(
          (item) => item.value !== "transparent",
        ),
      },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "switch",
    label: "Switch",
    description: "即时开关设置，如进度通知、离线缓存。",
    category: "input",
    view: "input/SwitchControl.vue",
    contract: "contracts/switch.json",
    example: {},
    controls: [
      { key: "label", label: "开关文案", control: "text" },
      { key: "modelValue", label: "已开启", control: "boolean" },
      {
        key: "color",
        label: "开启色 Token",
        control: "select",
        options: colorTokenOptions.filter(
          (item) => item.value !== "transparent",
        ),
      },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "menu",
    label: "Menu",
    description: "从有限业务选项中选择，如服务类型、负责人。",
    category: "input",
    view: "input/Menu.vue",
    contract: "contracts/menu.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "modelValue", label: "当前选择", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "clearable", label: "允许清除", control: "boolean" },
      { key: "open", label: "展开菜单", control: "boolean" },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "error", label: "错误提示", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "chip",
    label: "Chip",
    description: "列表中的状态标签，如进行中、即将超时。",
    category: "display",
    view: "display/Chip.vue",
    contract: "contracts/chip.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "badge",
    label: "Badge",
    description: "数量或状态角标，如未读数、已完成。",
    category: "display",
    view: "display/Badge.vue",
    contract: "contracts/badge.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
    ],
  },
  {
    id: "avatar",
    label: "Avatar",
    description: "人员标识，用于列表负责人或个人中心。",
    category: "display",
    view: "display/Avatar.vue",
    contract: "contracts/avatar.json",
    example: {},
    controls: [
      { key: "name", label: "姓名", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "颜色",
        control: "select",
        options: toneOptions.filter(
          (item) => item.value !== "error" && item.value !== "success",
        ),
      },
    ],
  },
  {
    id: "divider",
    label: "Divider",
    description: "分隔设置项或内容分区，可带中间标题。",
    category: "display",
    view: "display/Divider.vue",
    contract: "contracts/divider.json",
    example: {},
    controls: [
      { key: "label", label: "中间文案", control: "text" },
      { key: "inset", label: "左右缩进", control: "boolean" },
    ],
  },
  {
    id: "card",
    label: "Card",
    description:
      "只提供圆角 surface 的基础容器；内容完全由调用方的 slot 定义。",
    category: "display",
    view: "display/Card.vue",
    contract: "contracts/card.json",
    example: {},
    controls: [{ key: "elevated", label: "显示阴影", control: "boolean" }],
  },
  {
    id: "progress",
    label: "Progress",
    description: "展示任务进度，如附件上传或后台同步。",
    category: "display",
    view: "display/ProgressIndicator.vue",
    contract: "contracts/progress.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      { key: "value", label: "进度", control: "number" },
      { key: "indeterminate", label: "不确定进度", control: "boolean" },
    ],
  },
  {
    id: "empty-state",
    label: "Empty State",
    description: "无数据或无结果时给出说明与下一步操作。",
    category: "display",
    view: "display/EmptyState.vue",
    contract: "contracts/empty-state.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "description", label: "说明", control: "text" },
      { key: "actionLabel", label: "操作按钮", control: "text" },
    ],
  },
  {
    id: "spinner",
    label: "Spinner",
    description: "行内或整页加载等待反馈。",
    category: "display",
    view: "display/Spinner.vue",
    contract: "contracts/spinner.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
    ],
  },
  {
    id: "app-bar",
    label: "App Bar",
    description: "移动端页顶导航：首页工作台，或详情页返回与操作。",
    category: "navigation",
    view: "navigation/AppBar.vue",
    contract: "contracts/app-bar.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "dense", label: "紧凑", control: "boolean" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
      { key: "showBack", label: "显示返回键", control: "boolean" },
      { key: "showAction", label: "显示右侧操作", control: "boolean" },
      {
        key: "actionIcon",
        label: "右侧操作图标",
        control: "select",
        options: [
          { label: "更多", value: "more" },
          { label: "新建", value: "plus" },
          { label: "搜索", value: "search" },
          { label: "设置", value: "settings" },
        ],
      },
    ],
  },
  {
    id: "primary-tabs",
    label: "一级 Tab",
    description: "页内主分区：Liquid Glass 胶囊标出当前视图。",
    category: "navigation",
    view: "navigation/PrimaryTabs.vue",
    contract: "contracts/primary-tabs.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前 Tab",
        control: "select",
        options: [
          { label: "概览", value: "overview" },
          { label: "活动", value: "activity" },
          { label: "数据", value: "data" },
          { label: "设置", value: "settings" },
        ],
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "showIndicator", label: "显示底部滑线", control: "boolean" },
      { key: "showDivider", label: "显示底部分隔线", control: "boolean" },
      { key: "grow", label: "等宽铺满", control: "boolean" },
      { key: "swipe", label: "触摸滑动切换", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动切换", control: "boolean" },
      { key: "fill", label: "撑满可用高度", control: "boolean" },
    ],
  },
  {
    id: "secondary-tabs",
    label: "二级 Tab",
    description: "页内子分区：文字下方的居中小三角标出当前视图。",
    category: "navigation",
    view: "navigation/SecondaryTabs.vue",
    contract: "contracts/secondary-tabs.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前 Tab",
        control: "select",
        options: [
          { label: "概览", value: "overview" },
          { label: "活动", value: "activity" },
          { label: "记录", value: "records" },
          { label: "附件", value: "attachments" },
        ],
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "showDivider", label: "显示底部分隔线", control: "boolean" },
      { key: "grow", label: "等宽铺满", control: "boolean" },
      { key: "swipe", label: "触摸滑动切换", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动切换", control: "boolean" },
      { key: "fill", label: "撑满可用高度", control: "boolean" },
    ],
  },
  {
    id: "filter-bar",
    label: "三级 Tab（Filter Bar）",
    description: "只改变当前数据集合的快捷筛选，不切换视图区。",
    category: "navigation",
    view: "navigation/FilterBar.vue",
    contract: "contracts/filter-bar.json",
    example: {},
    controls: [{ key: "modelValue", label: "当前筛选", control: "text" }],
  },
  {
    id: "tabbar",
    label: "Tabbar",
    description: "应用根目的地导航：视图区在上，底部只负责目的地切换。",
    category: "navigation",
    view: "navigation/Tabbar.vue",
    contract: "contracts/tabbar.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前入口",
        control: "select",
        options: [
          { label: "首页", value: "home" },
          { label: "任务", value: "tasks" },
          { label: "我的", value: "profile" },
        ],
      },
      { key: "grow", label: "等宽铺满", control: "boolean" },
    ],
  },
  {
    id: "tab-viewport",
    label: "Tab Viewport",
    description: "与导航解耦的内容视图，负责保活、转场与横向手势。",
    category: "navigation",
    view: "navigation/TabViewport.vue",
    contract: "contracts/tab-viewport.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前视图",
        control: "select",
        options: [
          { label: "第一屏", value: "one" },
          { label: "第二屏", value: "two" },
          { label: "第三屏", value: "three" },
        ],
      },
      { key: "swipe", label: "触摸滑动", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动", control: "boolean" },
      { key: "keepMounted", label: "内容保活", control: "boolean" },
      { key: "transitionDuration", label: "转场时长", control: "number" },
    ],
  },
  {
    id: "data-list",
    label: "Data List",
    description:
      "列表外观容器：surface、圆角、分隔与阴影。行内容由业务提供；可滚动场景请外层组合 ScrollableDataList。",
    category: "data",
    view: "data/DataList.vue",
    contract: "contracts/data-list.json",
    example: {},
    controls: [
      { key: "divided", label: "显示分隔线", control: "boolean" },
      { key: "inset", label: "内容缩进", control: "boolean" },
      {
        key: "surface",
        label: "容器表面",
        control: "select",
        options: [
          { label: "透明", value: "none" },
          { label: "默认", value: "default" },
          { label: "抬升", value: "raised" },
        ],
      },
      {
        key: "rounded",
        label: "圆角层级",
        control: "select",
        options: [
          { label: "无", value: "none" },
          { label: "小", value: "sm" },
          { label: "中", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "scrollable-data-list",
    label: "Scrollable Data List",
    description:
      "滚动壳：下拉刷新与触底加载。不负责列表外观；内部再组合 DataList（或任意业务结构）承载行内容。",
    category: "data",
    view: "data/ScrollableDataList.vue",
    contract: "contracts/scrollable-data-list.json",
    example: {},
    controls: [
      { key: "pullRefresh", label: "下拉刷新", control: "boolean" },
      { key: "loadMore", label: "触底加载", control: "boolean" },
      { key: "dragScroll", label: "鼠标拖拽滚动", control: "boolean" },
      { key: "refreshing", label: "刷新中", control: "boolean" },
      { key: "loadingMore", label: "加载更多中", control: "boolean" },
      { key: "hasMore", label: "仍有更多", control: "boolean" },
      { key: "disabled", label: "禁用交互", control: "boolean" },
    ],
  },
  {
    id: "toast",
    label: "Toast",
    description: "轻量成败反馈，不打断当前页面上下文。",
    category: "feedback",
    view: "feedback/Toast.vue",
    contract: "contracts/toast.json",
    example: {},
    controls: [
      { key: "modelValue", label: "显示", control: "boolean" },
      { key: "message", label: "提示内容", control: "text" },
    ],
  },
  {
    id: "confirm",
    label: "Dialog / Confirm",
    description: "需要确认或知悉的打断式说明，如完成工单、离线提示。",
    category: "feedback",
    view: "feedback/ConfirmDialog.vue",
    contract: "contracts/confirm.json",
    example: {},
    controls: [
      { key: "modelValue", label: "已打开", control: "boolean" },
      { key: "title", label: "标题", control: "text" },
      { key: "message", label: "说明", control: "text" },
      { key: "confirmLabel", label: "确认按钮", control: "text" },
    ],
  },
  {
    id: "bottom-sheet",
    label: "Bottom Sheet",
    description: "从底部展开的临时面板，用于筛选或更多操作。",
    category: "feedback",
    view: "feedback/BottomSheet.vue",
    contract: "contracts/bottom-sheet.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "modelValue", label: "打开", control: "boolean" },
    ],
  },
  {
    id: "flow-sheet",
    label: "Flow Sheet",
    description: "底部多步面板，页内左右滑动切换步骤。",
    category: "feedback",
    view: "feedback/FlowSheet.vue",
    contract: "contracts/flow-sheet.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "modelValue", label: "打开", control: "boolean" },
      { key: "step", label: "当前步骤", control: "number" },
      { key: "stepCount", label: "步骤数", control: "number" },
      { key: "swipe", label: "允许滑动", control: "boolean" },
    ],
  },
  {
    id: "loading",
    label: "Loading",
    description: "蒙层加载反馈，阻断下层操作；局部不阻断请用 Spinner。",
    category: "feedback",
    view: "feedback/Loading.vue",
    contract: "contracts/loading.json",
    example: {},
    controls: [
      { key: "modelValue", label: "打开", control: "boolean" },
      { key: "label", label: "说明", control: "text" },
    ],
  },
] satisfies ComponentRecord[];
