import type { ComponentRecord } from "@/design-system/types";

const toneOptions = [
  { label: "Primary (color.primary)", value: "primary" },
  { label: "Secondary (color.secondary)", value: "secondary" },
  { label: "Error (color.error)", value: "error" },
  { label: "Success (color.success)", value: "success" },
];

const sizeOptions = [
  { label: "小", value: "sm" },
  { label: "标准", value: "md" },
  { label: "大", value: "lg" },
];

export const componentRecords = [
  {
    id: "button",
    label: "按钮",
    category: "basic",
    view: "basic/Button.vue",
    contract: "contracts/button.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "variant",
        label: "样式",
        control: "select",
        options: [
          { label: "Flat", value: "flat" },
          { label: "Tonal", value: "tonal" },
          { label: "Outlined", value: "outlined" },
          { label: "Text", value: "text" },
        ],
      },
      { key: "tone", label: "语义色", control: "select", options: toneOptions },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "block", label: "占满宽度", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "icon-button",
    label: "图标按钮",
    category: "basic",
    view: "basic/IconButton.vue",
    contract: "contracts/icon-button.json",
    example: {},
    controls: [
      { key: "ariaLabel", label: "无障碍名称", control: "text" },
      {
        key: "icon",
        label: "图标",
        control: "select",
        options: [
          { label: "More", value: "more" },
          { label: "Plus", value: "plus" },
          { label: "Search", value: "search" },
          { label: "Settings", value: "settings" },
        ],
      },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "SM", value: "sm" },
          { label: "MD", value: "md" },
          { label: "LG", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          { label: "Neutral (color.on-surface)", value: "neutral" },
          { label: "Primary (color.primary)", value: "primary" },
          { label: "Secondary (color.secondary)", value: "secondary" },
        ],
      },
      {
        key: "variant",
        label: "样式",
        control: "select",
        options: [
          { label: "柔和背景", value: "tonal" },
          { label: "实色背景", value: "flat" },
          { label: "描边", value: "outlined" },
          { label: "透明", value: "text" },
        ],
      },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "text-field",
    label: "文本框",
    category: "basic",
    view: "basic/TextField.vue",
    contract: "contracts/text-field.json",
    example: {},
    controls: [
      { key: "label", label: "标签", control: "text" },
      { key: "modelValue", label: "值", control: "text" },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "chip",
    label: "Chip",
    category: "basic",
    view: "basic/Chip.vue",
    contract: "contracts/chip.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "card",
    label: "Card",
    category: "basic",
    view: "basic/Card.vue",
    contract: "contracts/card.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "subtitle", label: "副标题", control: "text" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "app-bar",
    label: "App Bar",
    category: "complex",
    view: "complex/AppBar.vue",
    contract: "contracts/app-bar.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "dense", label: "紧凑", control: "boolean" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
      { key: "showBack", label: "显示返回键", control: "boolean" },
      { key: "showAction", label: "显示右侧操作", control: "boolean" },
      { key: "actionLabel", label: "右侧操作名称", control: "text" },
    ],
  },
  {
    id: "tabs",
    label: "Tabs",
    category: "complex",
    view: "complex/Tabs.vue",
    contract: "contracts/tabs.json",
    example: {},
    controls: [
      { key: "modelValue", label: "当前 Tab", control: "text" },
      {
        key: "selectionStyle",
        label: "选中样式",
        control: "select",
        options: [
          { label: "全圆弧", value: "pill" },
          { label: "底部滑线", value: "underline" },
          { label: "仅文字", value: "text" },
        ],
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "showIndicator", label: "显示底部滑线", control: "boolean" },
      { key: "showDivider", label: "显示底部分隔线", control: "boolean" },
      { key: "grow", label: "等宽铺满", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动切换", control: "boolean" },
    ],
  },
  {
    id: "data-list",
    label: "Data List",
    category: "complex",
    view: "complex/DataList.vue",
    contract: "contracts/data-list.json",
    example: {},
    controls: [
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "emptyText", label: "空态文案", control: "text" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
      { key: "showActions", label: "显示行尾按钮", control: "boolean" },
    ],
  },
  {
    id: "bottom-sheet",
    label: "Bottom Sheet",
    category: "complex",
    view: "complex/BottomSheet.vue",
    contract: "contracts/bottom-sheet.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "modelValue", label: "打开", control: "boolean" },
    ],
  },
  {
    id: "select",
    label: "Select",
    category: "basic",
    view: "basic/SelectField.vue",
    contract: "contracts/select.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "modelValue", label: "当前选择", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "clearable", label: "允许清除", control: "boolean" },
      { key: "open", label: "展开菜单", control: "boolean" },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "error", label: "错误提示", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "textarea",
    label: "Textarea",
    category: "basic",
    view: "basic/Textarea.vue",
    contract: "contracts/textarea.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "modelValue", label: "输入内容", control: "text" },
      { key: "rows", label: "显示行数", control: "number" },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "checkbox",
    label: "Checkbox",
    category: "basic",
    view: "basic/Checkbox.vue",
    contract: "contracts/checkbox.json",
    example: {},
    controls: [
      { key: "label", label: "选项文案", control: "text" },
      { key: "modelValue", label: "已选中", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "radio-group",
    label: "Radio Group",
    category: "basic",
    view: "basic/RadioGroup.vue",
    contract: "contracts/radio-group.json",
    example: {},
    controls: [
      { key: "label", label: "分组名称", control: "text" },
      { key: "modelValue", label: "当前选项", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "switch",
    label: "Switch",
    category: "basic",
    view: "basic/SwitchControl.vue",
    contract: "contracts/switch.json",
    example: {},
    controls: [
      { key: "label", label: "开关文案", control: "text" },
      { key: "modelValue", label: "已开启", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "avatar",
    label: "Avatar",
    category: "basic",
    view: "basic/Avatar.vue",
    contract: "contracts/avatar.json",
    example: {},
    controls: [
      { key: "name", label: "姓名", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "颜色",
        control: "select",
        options: toneOptions.filter(
          (item) => item.value !== "error" && item.value !== "success",
        ),
      },
    ],
  },
  {
    id: "badge",
    label: "Badge",
    category: "basic",
    view: "basic/Badge.vue",
    contract: "contracts/badge.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
    ],
  },
  {
    id: "divider",
    label: "Divider",
    category: "basic",
    view: "basic/Divider.vue",
    contract: "contracts/divider.json",
    example: {},
    controls: [
      { key: "label", label: "中间文案", control: "text" },
      { key: "inset", label: "左右缩进", control: "boolean" },
    ],
  },
  {
    id: "progress",
    label: "Progress",
    category: "basic",
    view: "basic/ProgressIndicator.vue",
    contract: "contracts/progress.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      { key: "value", label: "进度", control: "number" },
      { key: "indeterminate", label: "不确定进度", control: "boolean" },
    ],
  },
  {
    id: "spinner",
    label: "Spinner",
    category: "basic",
    view: "basic/Spinner.vue",
    contract: "contracts/spinner.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
    ],
  },
  {
    id: "search-bar",
    label: "Search Bar",
    category: "complex",
    view: "complex/SearchBar.vue",
    contract: "contracts/search-bar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "搜索内容", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "filter-bar",
    label: "Filter Bar",
    category: "complex",
    view: "complex/FilterBar.vue",
    contract: "contracts/filter-bar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "当前筛选", control: "text" },
      { key: "showFilter", label: "显示高级筛选", control: "boolean" },
    ],
  },
  {
    id: "bottom-navigation",
    label: "Bottom Navigation",
    category: "complex",
    view: "complex/BottomNavigation.vue",
    contract: "contracts/bottom-navigation.json",
    example: {},
    controls: [
      { key: "modelValue", label: "当前入口", control: "text" },
      {
        key: "display",
        label: "内容形式",
        control: "select",
        options: [
          { label: "图标和文字", value: "icon-label" },
          { label: "纯图标", value: "icon" },
          { label: "纯文字", value: "label" },
        ],
      },
      { key: "showIndicator", label: "显示滑动指示器", control: "boolean" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
      { key: "showView", label: "显示内容视图", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动切换", control: "boolean" },
    ],
  },
  {
    id: "dialog",
    label: "Dialog",
    category: "complex",
    view: "complex/DialogPanel.vue",
    contract: "contracts/dialog.json",
    example: {},
    controls: [
      { key: "modelValue", label: "已打开", control: "boolean" },
      { key: "title", label: "标题", control: "text" },
      { key: "message", label: "说明", control: "text" },
      { key: "confirmLabel", label: "确认按钮", control: "text" },
    ],
  },
  {
    id: "snackbar",
    label: "Snackbar / Toast",
    category: "complex",
    view: "complex/SnackbarToast.vue",
    contract: "contracts/snackbar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "显示", control: "boolean" },
      { key: "message", label: "提示内容", control: "text" },
      {
        key: "tone",
        label: "反馈类型",
        control: "select",
        options: [
          { label: "成功", value: "success" },
          { label: "错误", value: "error" },
          { label: "信息", value: "info" },
        ],
      },
    ],
  },
  {
    id: "empty-state",
    label: "Empty State",
    category: "complex",
    view: "complex/EmptyState.vue",
    contract: "contracts/empty-state.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "description", label: "说明", control: "text" },
      { key: "actionLabel", label: "操作按钮", control: "text" },
    ],
  },
  {
    id: "form-section",
    label: "Form Section",
    category: "complex",
    view: "complex/FormSection.vue",
    contract: "contracts/form-section.json",
    example: {},
    controls: [
      { key: "title", label: "分组标题", control: "text" },
      { key: "description", label: "说明", control: "text" },
      { key: "required", label: "必填", control: "boolean" },
      { key: "actionLabel", label: "右侧操作", control: "text" },
    ],
  },
] satisfies ComponentRecord[];
