import type { ComponentRecord } from "@/design-system/types";

const toneOptions = [
  { label: "Primary (color.primary)", value: "primary" },
  { label: "Secondary (color.secondary)", value: "secondary" },
  { label: "Error (color.error)", value: "error" },
  { label: "Success (color.success)", value: "success" },
];

const buttonToneOptions = [
  { label: "Action (color.action)", value: "action" },
  ...toneOptions,
];

const sizeOptions = [
  { label: "小", value: "sm" },
  { label: "标准", value: "md" },
  { label: "大", value: "lg" },
];

export const componentRecords = [
  {
    id: "button",
    label: "Button",
    description: "表单主次操作，如提交工单、保存草稿。",
    category: "basic",
    view: "basic/Button.vue",
    contract: "contracts/button.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "variant",
        label: "样式",
        control: "select",
        options: [
          { label: "Flat", value: "flat" },
          { label: "Tonal", value: "tonal" },
          { label: "Outlined", value: "outlined" },
          { label: "Text", value: "text" },
        ],
      },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: buttonToneOptions,
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "block", label: "占满宽度", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "icon-button",
    label: "Icon Button",
    description: "顶栏与工具区的紧凑图标操作，如更多、新建。",
    category: "basic",
    view: "basic/IconButton.vue",
    contract: "contracts/icon-button.json",
    example: {},
    controls: [
      { key: "ariaLabel", label: "无障碍名称", control: "text" },
      {
        key: "icon",
        label: "图标",
        control: "select",
        options: [
          { label: "More", value: "more" },
          { label: "Plus", value: "plus" },
          { label: "Search", value: "search" },
          { label: "Settings", value: "settings" },
        ],
      },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "SM", value: "sm" },
          { label: "MD", value: "md" },
          { label: "LG", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          { label: "Secondary (color.secondary)", value: "secondary" },
          { label: "Primary (color.primary)", value: "primary" },
        ],
      },
      {
        key: "variant",
        label: "样式",
        control: "select",
        options: [
          { label: "柔和背景", value: "tonal" },
          { label: "实色背景", value: "flat" },
          { label: "描边", value: "outlined" },
          { label: "透明", value: "text" },
        ],
      },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "text-field",
    label: "Text Field",
    description: "采集单行业务信息，如联系人、电话。",
    category: "basic",
    view: "basic/TextField.vue",
    contract: "contracts/text-field.json",
    example: {},
    controls: [
      { key: "label", label: "标签", control: "text" },
      { key: "modelValue", label: "值", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "chip",
    label: "Chip",
    description: "列表中的状态标签，如进行中、即将超时。",
    category: "basic",
    view: "basic/Chip.vue",
    contract: "contracts/chip.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "card",
    label: "Card",
    description: "承载业务摘要与信息区块，如今日工单、客户信息。",
    category: "basic",
    view: "basic/Card.vue",
    contract: "contracts/card.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "subtitle", label: "副标题", control: "text" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "app-bar",
    label: "App Bar",
    description: "移动端页顶导航：首页工作台，或详情页返回与操作。",
    category: "complex",
    view: "complex/AppBar.vue",
    contract: "contracts/app-bar.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "dense", label: "紧凑", control: "boolean" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
      { key: "showBack", label: "显示返回键", control: "boolean" },
      { key: "showAction", label: "显示右侧操作", control: "boolean" },
      {
        key: "actionIcon",
        label: "右侧操作图标",
        control: "select",
        options: [
          { label: "更多", value: "more" },
          { label: "新建", value: "plus" },
          { label: "搜索", value: "search" },
          { label: "设置", value: "settings" },
        ],
      },
    ],
  },
  {
    id: "tabs",
    label: "Tabs",
    description: "页内二级切换：详情分区，或列表顶等宽分段筛选。",
    category: "complex",
    view: "complex/Tabs.vue",
    contract: "contracts/tabs.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前 Tab",
        control: "select",
        options: [
          { label: "概览", value: "overview" },
          { label: "活动", value: "activity" },
        ],
      },
      {
        key: "selectionStyle",
        label: "选中样式",
        control: "select",
        options: [
          { label: "全圆弧", value: "pill" },
          { label: "底部滑线", value: "underline" },
          { label: "仅文字", value: "text" },
        ],
      },
      { key: "size", label: "尺寸", control: "select", options: sizeOptions },
      { key: "showIndicator", label: "显示底部滑线", control: "boolean" },
      { key: "showDivider", label: "显示底部分隔线", control: "boolean" },
      { key: "grow", label: "等宽铺满", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动切换", control: "boolean" },
    ],
  },
  {
    id: "data-list",
    label: "Data List",
    description: "仅建立列表容器、分隔与表面层级，行内容完全由业务提供。",
    category: "complex",
    view: "complex/DataList.vue",
    contract: "contracts/data-list.json",
    example: {},
    controls: [
      { key: "divided", label: "显示分隔线", control: "boolean" },
      { key: "inset", label: "内容缩进", control: "boolean" },
      {
        key: "surface",
        label: "容器表面",
        control: "select",
        options: [
          { label: "透明", value: "none" },
          { label: "默认", value: "default" },
          { label: "抬升", value: "raised" },
        ],
      },
      {
        key: "rounded",
        label: "圆角层级",
        control: "select",
        options: [
          { label: "无", value: "none" },
          { label: "小", value: "sm" },
          { label: "中", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "scrollable-data-list",
    label: "Scrollable Data List",
    description: "为任意业务列表提供可配置的下拉刷新与触底加载。",
    category: "complex",
    view: "complex/ScrollableDataList.vue",
    contract: "contracts/scrollable-data-list.json",
    example: {},
    controls: [
      { key: "pullRefresh", label: "下拉刷新", control: "boolean" },
      { key: "loadMore", label: "触底加载", control: "boolean" },
      { key: "refreshing", label: "刷新中", control: "boolean" },
      { key: "loadingMore", label: "加载更多中", control: "boolean" },
      { key: "hasMore", label: "仍有更多", control: "boolean" },
      { key: "disabled", label: "禁用交互", control: "boolean" },
    ],
  },
  {
    id: "tab-viewport",
    label: "Tab Viewport",
    description: "与导航解耦的内容视图，负责保活、转场与横向手势。",
    category: "complex",
    view: "complex/TabViewport.vue",
    contract: "contracts/tab-viewport.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前视图",
        control: "select",
        options: [
          { label: "第一屏", value: "one" },
          { label: "第二屏", value: "two" },
          { label: "第三屏", value: "three" },
        ],
      },
      { key: "swipe", label: "触摸滑动", control: "boolean" },
      { key: "mouseSwipe", label: "鼠标拖动", control: "boolean" },
      { key: "keepMounted", label: "内容保活", control: "boolean" },
      { key: "transitionDuration", label: "转场时长", control: "number" },
    ],
  },
  {
    id: "bottom-sheet",
    label: "Bottom Sheet",
    description: "从底部展开的临时面板，用于筛选或更多操作。",
    category: "complex",
    view: "complex/BottomSheet.vue",
    contract: "contracts/bottom-sheet.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "modelValue", label: "打开", control: "boolean" },
    ],
  },
  {
    id: "select",
    label: "Select",
    description: "从有限业务选项中选择，如服务类型、负责人。",
    category: "basic",
    view: "basic/SelectField.vue",
    contract: "contracts/select.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "modelValue", label: "当前选择", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "clearable", label: "允许清除", control: "boolean" },
      { key: "open", label: "展开菜单", control: "boolean" },
      { key: "loading", label: "加载中", control: "boolean" },
      { key: "error", label: "错误提示", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "textarea",
    label: "Textarea",
    description: "填写多行说明，如问题描述、现场备注。",
    category: "basic",
    view: "basic/Textarea.vue",
    contract: "contracts/textarea.json",
    example: {},
    controls: [
      { key: "label", label: "字段名称", control: "text" },
      { key: "modelValue", label: "输入内容", control: "text" },
      { key: "rows", label: "显示行数", control: "number" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "checkbox",
    label: "Checkbox",
    description: "独立确认项，如提交前核对、业务偏好勾选。",
    category: "basic",
    view: "basic/Checkbox.vue",
    contract: "contracts/checkbox.json",
    example: {},
    controls: [
      { key: "label", label: "选项文案", control: "text" },
      { key: "modelValue", label: "已选中", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "radio-group",
    label: "Radio Group",
    description: "互斥单选，如工单优先级、上门时段。",
    category: "basic",
    view: "basic/RadioGroup.vue",
    contract: "contracts/radio-group.json",
    example: {},
    controls: [
      { key: "label", label: "分组名称", control: "text" },
      { key: "modelValue", label: "当前选项", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "switch",
    label: "Switch",
    description: "即时开关设置，如进度通知、离线缓存。",
    category: "basic",
    view: "basic/SwitchControl.vue",
    contract: "contracts/switch.json",
    example: {},
    controls: [
      { key: "label", label: "开关文案", control: "text" },
      { key: "modelValue", label: "已开启", control: "boolean" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "avatar",
    label: "Avatar",
    description: "人员标识，用于列表负责人或个人中心。",
    category: "basic",
    view: "basic/Avatar.vue",
    contract: "contracts/avatar.json",
    example: {},
    controls: [
      { key: "name", label: "姓名", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
      {
        key: "tone",
        label: "颜色",
        control: "select",
        options: toneOptions.filter(
          (item) => item.value !== "error" && item.value !== "success",
        ),
      },
    ],
  },
  {
    id: "badge",
    label: "Badge",
    description: "数量或状态角标，如未读数、已完成。",
    category: "basic",
    view: "basic/Badge.vue",
    contract: "contracts/badge.json",
    example: {},
    controls: [
      { key: "label", label: "文案", control: "text" },
      {
        key: "tone",
        label: "语义色",
        control: "select",
        options: [
          ...toneOptions,
          { label: "Warning (color.warning)", value: "warning" },
        ],
      },
    ],
  },
  {
    id: "divider",
    label: "Divider",
    description: "分隔设置项或内容分区，可带中间标题。",
    category: "basic",
    view: "basic/Divider.vue",
    contract: "contracts/divider.json",
    example: {},
    controls: [
      { key: "label", label: "中间文案", control: "text" },
      { key: "inset", label: "左右缩进", control: "boolean" },
    ],
  },
  {
    id: "progress",
    label: "Progress",
    description: "展示任务进度，如附件上传或后台同步。",
    category: "basic",
    view: "basic/ProgressIndicator.vue",
    contract: "contracts/progress.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      { key: "value", label: "进度", control: "number" },
      { key: "indeterminate", label: "不确定进度", control: "boolean" },
    ],
  },
  {
    id: "spinner",
    label: "Spinner",
    description: "行内或整页加载等待反馈。",
    category: "basic",
    view: "basic/Spinner.vue",
    contract: "contracts/spinner.json",
    example: {},
    controls: [
      { key: "label", label: "说明", control: "text" },
      {
        key: "size",
        label: "尺寸",
        control: "select",
        options: [
          { label: "小", value: "sm" },
          { label: "标准", value: "md" },
          { label: "大", value: "lg" },
        ],
      },
    ],
  },
  {
    id: "search-bar",
    label: "Search Bar",
    description: "在列表顶部按编号或客户搜索，支持清除。",
    category: "complex",
    view: "complex/SearchBar.vue",
    contract: "contracts/search-bar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "搜索内容", control: "text" },
      { key: "placeholder", label: "提示文案", control: "text" },
      { key: "disabled", label: "禁用", control: "boolean" },
    ],
  },
  {
    id: "filter-bar",
    label: "Filter Bar",
    description: "快捷状态筛选，并可挂接高级筛选入口。",
    category: "complex",
    view: "complex/FilterBar.vue",
    contract: "contracts/filter-bar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "当前筛选", control: "text" },
      { key: "showFilter", label: "显示高级筛选", control: "boolean" },
    ],
  },
  {
    id: "bottom-navigation",
    label: "Bottom Navigation",
    description: "应用主 Tabbar：入口数量、文案与图标均由外部传入。",
    category: "complex",
    view: "complex/BottomNavigation.vue",
    contract: "contracts/bottom-navigation.json",
    example: {},
    controls: [
      {
        key: "modelValue",
        label: "当前入口",
        control: "select",
        options: [
          { label: "首页", value: "one" },
          { label: "列表", value: "two" },
          { label: "我的", value: "three" },
        ],
      },
      {
        key: "display",
        label: "内容形式",
        control: "select",
        options: [
          { label: "图标和文字", value: "icon-label" },
          { label: "纯图标", value: "icon" },
          { label: "纯文字", value: "label" },
        ],
      },
      { key: "showIndicator", label: "显示顶部指示器", control: "boolean" },
      { key: "elevated", label: "显示阴影", control: "boolean" },
    ],
  },
  {
    id: "dialog",
    label: "Dialog",
    description: "需要确认或知悉的打断式说明，如完成工单、离线提示。",
    category: "complex",
    view: "complex/DialogPanel.vue",
    contract: "contracts/dialog.json",
    example: {},
    controls: [
      { key: "modelValue", label: "已打开", control: "boolean" },
      { key: "title", label: "标题", control: "text" },
      { key: "message", label: "说明", control: "text" },
      { key: "confirmLabel", label: "确认按钮", control: "text" },
    ],
  },
  {
    id: "snackbar",
    label: "Snackbar / Toast",
    description: "轻量成败反馈，不打断当前页面上下文。",
    category: "complex",
    view: "complex/SnackbarToast.vue",
    contract: "contracts/snackbar.json",
    example: {},
    controls: [
      { key: "modelValue", label: "显示", control: "boolean" },
      { key: "message", label: "提示内容", control: "text" },
      {
        key: "tone",
        label: "反馈类型",
        control: "select",
        options: [
          { label: "成功", value: "success" },
          { label: "错误", value: "error" },
          { label: "信息", value: "info" },
        ],
      },
    ],
  },
  {
    id: "empty-state",
    label: "Empty State",
    description: "无数据或无结果时给出说明与下一步操作。",
    category: "complex",
    view: "complex/EmptyState.vue",
    contract: "contracts/empty-state.json",
    example: {},
    controls: [
      { key: "title", label: "标题", control: "text" },
      { key: "description", label: "说明", control: "text" },
      { key: "actionLabel", label: "操作按钮", control: "text" },
    ],
  },
  {
    id: "form-section",
    label: "Form Section",
    description: "表单分组：必填客户信息，或可选补充信息。",
    category: "complex",
    view: "complex/FormSection.vue",
    contract: "contracts/form-section.json",
    example: {},
    controls: [
      { key: "title", label: "分组标题", control: "text" },
      { key: "description", label: "说明", control: "text" },
      { key: "required", label: "必填", control: "boolean" },
      { key: "actionLabel", label: "右侧操作", control: "text" },
    ],
  },
] satisfies ComponentRecord[];
