import type { PrototypeRecord, ScreenRecord } from "@/design-system/types";

export const prototypes = [
  {
    id: "field-service",
    label: "现场服务工单",
    lifecycle: "active",
    owners: ["产品设计"],
    roles: ["现场工程师", "调度", "客户"],
    defaultThemeId: "light",
  },
  {
    id: "project",
    label: "项目协作",
    lifecycle: "active",
    owners: ["产品"],
    roles: ["UI", "DE", "QA"],
    defaultThemeId: "light",
  },
] satisfies PrototypeRecord[];

export const prototypeScreens = [
  {
    prototypeId: "field-service",
    screenId: "field-service.dashboard",
    screenSlug: "dashboard",
    label: "工单工作台",
    title: "现场服务工作台",
    path: "/prototype/field-service/dashboard",
    view: "field-service/screens/Dashboard.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.work-orders",
    screenSlug: "work-orders",
    label: "工单列表",
    title: "工单列表",
    path: "/prototype/field-service/work-orders",
    view: "field-service/screens/WorkOrderList.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
      { id: "error", label: "错误" },
      { id: "filtered", label: "筛选结果" },
      { id: "high-priority", label: "高优先级" },
      { id: "overdue", label: "已超时" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.work-order-detail",
    screenSlug: "work-order-detail",
    label: "工单详情",
    title: "工单详情",
    path: "/prototype/field-service/work-order-detail",
    view: "field-service/screens/WorkOrderDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "error", label: "错误" },
      { id: "high-priority", label: "高优先级" },
      { id: "overdue", label: "已超时" },
      { id: "sheet-open", label: "Bottom Sheet 打开" },
      { id: "dialog-open", label: "Dialog 打开" },
      { id: "toast-open", label: "Toast 显示" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.create-work-order",
    screenSlug: "create-work-order",
    label: "新建工单",
    title: "新建工单",
    path: "/prototype/field-service/create-work-order",
    view: "field-service/screens/CreateWorkOrder.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "validation-error", label: "校验失败" },
      { id: "toast-open", label: "提交成功 Toast" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.customer-detail",
    screenSlug: "customer-detail",
    label: "客户详情",
    title: "客户详情",
    path: "/prototype/field-service/customer-detail",
    view: "field-service/screens/CustomerDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "无服务记录" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.messages",
    screenSlug: "messages",
    label: "消息中心",
    title: "消息中心",
    path: "/prototype/field-service/messages",
    view: "field-service/screens/MessageCenter.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "unread", label: "未读消息" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.settings",
    screenSlug: "settings",
    label: "个人设置",
    title: "个人设置",
    path: "/prototype/field-service/settings",
    view: "field-service/screens/Settings.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "浅色" },
      { id: "dark", label: "深色状态" },
    ],
  },
  {
    prototypeId: "project",
    screenId: "project.task-list",
    screenSlug: "task-list",
    label: "任务列表",
    title: "任务列表",
    path: "/prototype/project/task-list",
    view: "project/screens/TaskList.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认态" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "project",
    screenId: "project.task-detail",
    screenSlug: "task-detail",
    label: "任务详情",
    title: "任务详情",
    path: "/prototype/project/task-detail",
    view: "project/screens/TaskDetail.vue",
    defaultVariantId: "overview",
    variants: [
      { id: "overview", label: "概览" },
      { id: "activity", label: "活动" },
      { id: "error", label: "错误" },
      { id: "sheet-open", label: "Sheet 打开" },
    ],
  },
] satisfies ScreenRecord[];
