import type { PrototypeRecord, ScreenRecord } from "@/design-system/types";

export const prototypes = [
  {
    id: "field-service",
    label: "现场服务工单",
    lifecycle: "active",
    owners: ["产品设计"],
    roles: ["现场工程师", "调度", "客户"],
    defaultThemeId: "light",
  },
  {
    id: "project",
    label: "项目协作",
    lifecycle: "active",
    owners: ["产品"],
    roles: ["UI", "DE", "QA"],
    defaultThemeId: "light",
  },
  {
    id: "ledger-planet",
    label: "账本星球",
    lifecycle: "active",
    owners: ["产品设计"],
    roles: ["个人用户"],
    defaultThemeId: "light",
  },
] satisfies PrototypeRecord[];

export const prototypeScreens = [
  {
    prototypeId: "field-service",
    screenId: "field-service.dashboard",
    screenSlug: "dashboard",
    label: "工单工作台",
    title: "现场服务工作台",
    path: "/prototype/field-service/dashboard",
    view: "field-service/screens/Dashboard.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.work-orders",
    screenSlug: "work-orders",
    label: "工单列表",
    title: "工单列表",
    path: "/prototype/field-service/work-orders",
    view: "field-service/screens/WorkOrderList.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
      { id: "error", label: "错误" },
      { id: "filtered", label: "筛选结果" },
      { id: "high-priority", label: "高优先级" },
      { id: "overdue", label: "已超时" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.work-order-detail",
    screenSlug: "work-order-detail",
    label: "工单详情",
    title: "工单详情",
    path: "/prototype/field-service/work-order-detail",
    view: "field-service/screens/WorkOrderDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "error", label: "错误" },
      { id: "high-priority", label: "高优先级" },
      { id: "overdue", label: "已超时" },
      { id: "sheet-open", label: "Bottom Sheet 打开" },
      { id: "dialog-open", label: "Dialog 打开" },
      { id: "toast-open", label: "Toast 显示" },
      { id: "created", label: "新建成功" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.create-work-order",
    screenSlug: "create-work-order",
    label: "新建工单",
    title: "新建工单",
    path: "/prototype/field-service/create-work-order",
    view: "field-service/screens/CreateWorkOrder.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "validation-error", label: "校验失败" },
      { id: "toast-open", label: "提交成功 Toast" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.customer-detail",
    screenSlug: "customer-detail",
    label: "客户详情",
    title: "客户详情",
    path: "/prototype/field-service/customer-detail",
    view: "field-service/screens/CustomerDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "无服务记录" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.messages",
    screenSlug: "messages",
    label: "消息中心",
    title: "消息中心",
    path: "/prototype/field-service/messages",
    view: "field-service/screens/MessageCenter.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "unread", label: "未读消息" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "field-service",
    screenId: "field-service.settings",
    screenSlug: "settings",
    label: "个人设置",
    title: "个人设置",
    path: "/prototype/field-service/settings",
    view: "field-service/screens/Settings.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "浅色" },
      { id: "dark", label: "深色状态" },
    ],
  },
  {
    prototypeId: "project",
    screenId: "project.task-list",
    screenSlug: "task-list",
    label: "任务列表",
    title: "任务列表",
    path: "/prototype/project/task-list",
    view: "project/screens/TaskList.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认态" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "project",
    screenId: "project.task-detail",
    screenSlug: "task-detail",
    label: "任务详情",
    title: "任务详情",
    path: "/prototype/project/task-detail",
    view: "project/screens/TaskDetail.vue",
    defaultVariantId: "overview",
    variants: [
      { id: "overview", label: "概览" },
      { id: "activity", label: "活动" },
      { id: "error", label: "错误" },
      { id: "sheet-open", label: "Sheet 打开" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.ledger-home",
    screenSlug: "ledger-home",
    label: "记账首页",
    title: "记账",
    path: "/prototype/ledger-planet/ledger-home",
    view: "ledger-planet/screens/TabRootScreen.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
      { id: "error", label: "错误" },
      { id: "filtered", label: "筛选结果" },
      { id: "sheet-open", label: "筛选 Sheet" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.record-edit",
    screenSlug: "record-edit",
    label: "记一笔",
    title: "记一笔",
    path: "/prototype/ledger-planet/record-edit",
    view: "ledger-planet/screens/RecordEdit.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "edit", label: "编辑" },
      { id: "validation-error", label: "校验失败" },
      { id: "toast-open", label: "保存成功" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.record-detail",
    screenSlug: "record-detail",
    label: "流水详情",
    title: "流水详情",
    path: "/prototype/ledger-planet/record-detail",
    view: "ledger-planet/screens/RecordDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "dialog-delete", label: "删除确认" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.analytics",
    screenSlug: "analytics",
    label: "图表分析",
    title: "图表分析",
    path: "/prototype/ledger-planet/analytics",
    view: "ledger-planet/screens/Analytics.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.benefits-home",
    screenSlug: "benefits-home",
    label: "权益首页",
    title: "权益",
    path: "/prototype/ledger-planet/benefits-home",
    view: "ledger-planet/screens/TabRootScreen.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.activity-detail",
    screenSlug: "activity-detail",
    label: "活动详情",
    title: "活动详情",
    path: "/prototype/ledger-planet/activity-detail",
    view: "ledger-planet/screens/ActivityDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "ended", label: "已结束" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.task-list",
    screenSlug: "task-list",
    label: "任务列表",
    title: "任务",
    path: "/prototype/ledger-planet/task-list",
    view: "ledger-planet/screens/TaskList.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "空态" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.task-detail",
    screenSlug: "task-detail",
    label: "任务详情",
    title: "任务详情",
    path: "/prototype/ledger-planet/task-detail",
    view: "ledger-planet/screens/TaskDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "completed", label: "已完成" },
      { id: "claimable", label: "可领奖" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.coupon-wallet",
    screenSlug: "coupon-wallet",
    label: "券包",
    title: "券包",
    path: "/prototype/ledger-planet/coupon-wallet",
    view: "ledger-planet/screens/CouponWallet.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "空态" },
      { id: "expired-tab", label: "已过期 Tab" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.coupon-detail",
    screenSlug: "coupon-detail",
    label: "券详情",
    title: "券详情",
    path: "/prototype/ledger-planet/coupon-detail",
    view: "ledger-planet/screens/CouponDetail.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "used", label: "已使用" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.me-home",
    screenSlug: "me-home",
    label: "我的",
    title: "我的",
    path: "/prototype/ledger-planet/me-home",
    view: "ledger-planet/screens/TabRootScreen.vue",
    defaultVariantId: "default",
    variants: [{ id: "default", label: "默认" }],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.wallet",
    screenSlug: "wallet",
    label: "钱包",
    title: "钱包",
    path: "/prototype/ledger-planet/wallet",
    view: "ledger-planet/screens/Wallet.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "empty", label: "空态" },
      { id: "hidden-balance", label: "隐藏余额" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.profile",
    screenSlug: "profile",
    label: "个人资料",
    title: "个人资料",
    path: "/prototype/ledger-planet/profile",
    view: "ledger-planet/screens/Profile.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "toast-saved", label: "保存成功" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.settings",
    screenSlug: "settings",
    label: "设置",
    title: "设置",
    path: "/prototype/ledger-planet/settings",
    view: "ledger-planet/screens/Settings.vue",
    defaultVariantId: "default",
    variants: [{ id: "default", label: "默认" }],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.help-center",
    screenSlug: "help-center",
    label: "帮助中心",
    title: "帮助中心",
    path: "/prototype/ledger-planet/help-center",
    view: "ledger-planet/screens/HelpCenter.vue",
    defaultVariantId: "default",
    variants: [{ id: "default", label: "默认" }],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.help-article",
    screenSlug: "help-article",
    label: "帮助文章",
    title: "帮助文章",
    path: "/prototype/ledger-planet/help-article",
    view: "ledger-planet/screens/HelpArticle.vue",
    defaultVariantId: "default",
    variants: [
      { id: "default", label: "默认" },
      { id: "loading", label: "加载中" },
      { id: "error", label: "错误" },
    ],
  },
  {
    prototypeId: "ledger-planet",
    screenId: "ledger-planet.about",
    screenSlug: "about",
    label: "关于",
    title: "关于",
    path: "/prototype/ledger-planet/about",
    view: "ledger-planet/screens/About.vue",
    defaultVariantId: "default",
    variants: [{ id: "default", label: "默认" }],
  },
] satisfies ScreenRecord[];
